INSERT INTO projects(title, category, funding_goal, start_date, end_date) VALUES("Project 1", "Tech", 100000, "April 10", "May 20");
INSERT INTO projects(title, category, funding_goal, start_date, end_date) VALUES("Project 2", "Culinary", 20000, "March 20", "April 10");
INSERT INTO projects(title, category, funding_goal, start_date, end_date) VALUES("Project 3", "Sports", 50000, "March 1", "March 30");
INSERT INTO projects(title, category, funding_goal, start_date, end_date) VALUES("Project 4", "Tech", 50000, "March 5", "March 25");
INSERT INTO projects(title, category, funding_goal, start_date, end_date) VALUES("Project 5", "Health", 25000, "February 6", "March 30");
INSERT INTO projects(title, category, funding_goal, start_date, end_date) VALUES("Project 6", "Health", 10000, "March 15", "April 1");
INSERT INTO projects(title, category, funding_goal, start_date, end_date) VALUES("Project 7", "Leisure", 30000, "March 20", "April 15");
INSERT INTO projects(title, category, funding_goal, start_date, end_date) VALUES("Project 8", "Health", 15000, "March1", "March 15");
INSERT INTO projects(title, category, funding_goal, start_date, end_date) VALUES("Project 9", "Early childhood", 10000, "April 1", "April 30");
INSERT INTO projects(title, category, funding_goal, start_date, end_date) VALUES("Project 10", "Culinary", 20000, "April 15", "May 10");

INSERT INTO users(name, age) VALUES("Abby", 90);
INSERT INTO users(name, age) VALUES("Mary", 53);
INSERT INTO users(name, age) VALUES("Sean", 45);
INSERT INTO users(name, age) VALUES("Sierra", 38);
INSERT INTO users(name, age) VALUES("Andre", 47);
INSERT INTO users(name, age) VALUES("Ana", 29);
INSERT INTO users(name, age) VALUES("Nate", 65);
INSERT INTO users(name, age) VALUES("Ed", 32);
INSERT INTO users(name, age) VALUES("Maura", 68);
INSERT INTO users(name, age) VALUES("Kris", 56);
INSERT INTO users(name, age) VALUES("Ella", 25);
INSERT INTO users(name, age) VALUES("Simon", 35);
INSERT INTO users(name, age) VALUES("Carrie", 56);
INSERT INTO users(name, age) VALUES("Diane", 48);
INSERT INTO users(name, age) VALUES("Bennie", 62);
INSERT INTO users(name, age) VALUES("Jack", 38);
INSERT INTO users(name, age) VALUES("Jane", 36);
INSERT INTO users(name, age) VALUES("Edgar", 49);
INSERT INTO users(name, age) VALUES("Allen", 50);
INSERT INTO users(name, age) VALUES("Poe", 51);

INSERT INTO pledges(amount, user_id, project_id) VALUES(5000, 2, 2);
INSERT INTO pledges(amount, user_id, project_id) VALUES(2000, 6, 1);
INSERT INTO pledges(amount, user_id, project_id) VALUES(10000, 20, 6);
INSERT INTO pledges(amount, user_id, project_id) VALUES(3000, 18, 8);
INSERT INTO pledges(amount, user_id, project_id) VALUES(9000, 9, 10);
INSERT INTO pledges(amount, user_id, project_id) VALUES(2000, 8, 3);
INSERT INTO pledges(amount, user_id, project_id) VALUES(1000, 3, 4);
INSERT INTO pledges(amount, user_id, project_id) VALUES(15000, 1, 10);
INSERT INTO pledges(amount, user_id, project_id) VALUES(4000, 12, 5);
INSERT INTO pledges(amount, user_id, project_id) VALUES(3000, 5, 7);
INSERT INTO pledges(amount, user_id, project_id) VALUES(10000, 19, 1);
INSERT INTO pledges(amount, user_id, project_id) VALUES(9000, 13, 9);
INSERT INTO pledges(amount, user_id, project_id) VALUES(6000, 17, 2);
INSERT INTO pledges(amount, user_id, project_id) VALUES(1000, 6, 3);
INSERT INTO pledges(amount, user_id, project_id) VALUES(2000, 16, 6);
INSERT INTO pledges(amount, user_id, project_id) VALUES(1000, 8, 4);
INSERT INTO pledges(amount, user_id, project_id) VALUES(10000, 15, 8);
INSERT INTO pledges(amount, user_id, project_id) VALUES(5000, 13, 5);
INSERT INTO pledges(amount, user_id, project_id) VALUES(5000, 5, 2);
INSERT INTO pledges(amount, user_id, project_id) VALUES(9000, 4, 6);
INSERT INTO pledges(amount, user_id, project_id) VALUES(15000, 14, 10);
INSERT INTO pledges(amount, user_id, project_id) VALUES(7000, 11, 2);
INSERT INTO pledges(amount, user_id, project_id) VALUES(1500, 20, 9);
INSERT INTO pledges(amount, user_id, project_id) VALUES(2500, 10, 6);
INSERT INTO pledges(amount, user_id, project_id) VALUES(500, 7, 7);
INSERT INTO pledges(amount, user_id, project_id) VALUES(1000, 3, 8);
INSERT INTO pledges(amount, user_id, project_id) VALUES(6500, 16, 6);
INSERT INTO pledges(amount, user_id, project_id) VALUES(3000, 19, 10);
INSERT INTO pledges(amount, user_id, project_id) VALUES(3500, 9, 7);
INSERT INTO pledges(amount, user_id, project_id) VALUES(9000, 20, 1);